### ISSUE TITLE
FR_30_V01: User progress tracking section

### ISSUE THREAD

**Issue by ccarnus** [ccarnus/brightminds#78]
**The Track section shall have a progress tracking dashboard. This dashboard shall display the progress that the user made compared to its learning objectives.**

- [x] The user shall have a percentage of its main objective to track its progress., like:

tracking: {
  progress: {type: String, default:0},
  objective: {type: String, required: true}
}

- [x] Their shall be an endpoint to retrieve the tracking section of a user
- [x] Their shall be an endpoint to modify the tracking section of a user for the objective
